### ISSUE TITLE
Export traces to Grafana

### ISSUE THREAD

**Issue by flemzord** [uptrace/cloud-changelog#7]
We use Uptrace and Grafana, we would like to have dashboards that also contain the traces. 
Would it be possible to have an export system or something to Grafana?

**Comment by vmihailenco** [comment]
Uptrace uses OpenTelemetry which was created just for this purpose. The idea is that both Grafana and Uptrace should accept data in OpenTelemetry format and you just configure your app to send data to both services/backends. You can add other services if needed too.

It can be done directly by configuring multiple exporters or by using a proxy like OpenTelemetry Collector. Grafana [docs](https://grafana.com/docs/opentelemetry/) should have relevant details.

>have dashboards that also contain the trace

Recently we added an ability to create metrics from spans so you can use those metrics in dashboards, for example, [here](https://app.uptrace.dev/metrics/1/817370621905207299?time_gte=20230127T035000&time_dur=10800&sort_by=spans_per_min&sort_desc=1) and [here](https://app.uptrace.dev/metrics/1/817370621905207300?time_gte=20230127T035100&time_dur=10800&sort_by=spans_per_min&sort_desc=1).

It is obviously not a Grafana yet, but I think we have some perks too so it might be an option. Just let me know what features from Grafana you are missing and we will add them to Uptrace.
